### ISSUE TITLE
Cannot read property 'concat' of undefined For Scalar

### ISSUE THREAD

**Issue by Fi1osof** [ardatan/graphql-import#230]
Bug.

Scalar Type definition does not exists fields. Example: Scalar Json. Scalar Upload.
On merge if Scalar define more that once, got error. I think, error here: https://github.com/prisma/graphql-import/blob/master/src/index.ts#L118
existingType.fields.concat.  existingType.fields is not defined.

**Comment by rojobuffalo** [comment]
I ran into this because I had `scalar DateTime` twice.

**Comment by ShiChenCong** [comment]
same to

**Comment by aaalsubaie** [comment]
I have the same error but I have only one Scalar!

**Comment by ardatan** [comment]
Hi @Fi1osof , @ShiChenCong and @aaalsubaie  !
In 1.0.0 beta release, we introduced a lot of changes including that fix related to the lack of `fields` in Scalar definitions.
Could you install `graphql-import@beta` to try new changes? Don't forget to modify your code regarding to the migration notes in `README`. 
https://github.com/ardatan/graphql-import#updating-from-07x

**Comment by ardatan** [comment]
Available in 1.0.0!
