### ISSUE TITLE
importSchema() to work with client side such as Apollo Client

### ISSUE THREAD

**Issue by webberwang** [ardatan/graphql-import#243]
How can we make importSchema work with the client side? It looks like Graphql Import supports only Node.js environment, so it's not working for the frontend.

```javascript
import { importSchema } from 'graphql-import'

const typeDefs = importSchema('./schema.graphql')

const client = new ApolloClient({
  clientState: {
    defaults,
    resolvers,
    typeDefs
  },
  uri: ``
})
```

The compilation errors:

```
./node_modules/graphql-import/node_modules/resolve-from/index.js

Module not found: Can't resolve 'module' in '/<projectRoot>/node_modules/graphql-import/node_modules/resolve-from'
```

**Comment by tuucan** [comment]
Could this be ever done? 👀

**Comment by marcus-sa** [comment]
@tuucan https://github.com/prisma/graphql-import-loader

**Comment by ardatan** [comment]
As @marcus-sa said, `graphql-import` loads GraphQL files using File System module of NodeJS which is not available in the browser. So, we use bundlers in client-side apps and it will be better to use a plugin for babel, webpack or rollup instead of `graphql-import`.
