### ISSUE TITLE
#import UserOrderByInput from '../../generated/prisma.graphql' Error Type UserOrderByInput  not found

### ISSUE THREAD

**Issue by YannisMarios** [ardatan/graphql-import#300]
Hi,

when I use:

```
# import UserOrderByInput from '../../generated/prisma.graphql' 

```

inside components/user/schema.graphql

I get the error:

```
Error: Type "UserOrderByInput"  not found

```

I want to import a type from a file inside a directory two levels up. Is this possible?

Thank you

**Comment by ardatan** [comment]
Hi @YannisMarios 
In 1.0.0 beta release, we introduced a lot of changes with a lot of bug fixes.
Could you install graphql-import@beta to try new changes? Don't forget to modify your code regarding to the migration notes in README.
https://github.com/ardatan/graphql-import#updating-from-07x

Let us know if your issue still persists.

**Comment by YannisMarios** [comment]
Hi, I haven't tried it because I finally ended up to use type-graphql with graphql-code-generator (https://graphql-code-generator.com)
