### ISSUE TITLE
Import not matching throw error

### ISSUE THREAD

**Issue by artentica** [ardatan/graphql-import#347]
Not possible to import fragment like that `#import "./fragments.graphql"` it's not matching the import line so it's throw error.

https://github.com/prisma/graphql-import/blob/212b9221e0e528aa2f5ca13d6d8188fd484219e2/src/index.ts#L44

**Comment by ardatan** [comment]
@artentica The correct syntax should be `import * from filename` without `"` but with `* from`.
I also added a better error message in the beta version so you can try it out.

Also in 1.0.0 beta release, we introduced a lot of changes.
Could you install graphql-import@beta to try new changes? Don't forget to modify your code regarding to the migration notes in README.
https://github.com/ardatan/graphql-import#updating-from-07x

Let us know if your issue still persists.
