### ISSUE TITLE
import * doesn't work with Root Fields

### ISSUE THREAD

**Issue by ralphchristianeclipse** [ardatan/graphql-import#370]
Can you make import * work including root fields.
```graphql
#import Mutation.*, Query.*, * from "./schema/auth.graphql"
#import Mutation.*, Query.*, Subscription.*, * from "./schema/user.graphql"
```
right now I'd have to do the above.

**Comment by ardatan** [comment]
Hi @ralphchristianeclipse  !
In 1.0.0 beta release, we introduced a lot of changes including a fix for this issue;
Could you install `graphql-import@beta` to try new changes? Don't forget to modify your code regarding to the migration notes in `README`. 
https://github.com/ardatan/graphql-import#updating-from-07xHi @ma-jahn !
In 1.0.0 beta release, we introduced a lot of changes including schema definition support;
Could you install `graphql-import@beta` to try new changes? Don't forget to modify your code regarding to the migration notes in `README`. 
https://github.com/ardatan/graphql-import#updating-from-07x

**Comment by ardatan** [comment]
Available in 1.0.0!

**Comment by flexlee** [comment]
The `import *` still doesn't work in 1.0.2. I have to
```
# import SpecificType, * from "./generated-schema/schema.graphql"
```
rather than
```
# import * from "./generated-schema/schema.graphql"
```

**Comment by ardatan** [comment]
@flexlee Could you open a seperate issue with a minimal reproduction? Thanks.
