### ISSUE TITLE
Expose graphql errors

### ISSUE THREAD

**Issue by Nexxado** [ardatan/graphql-import#39]
Using this library i got the following error when trying to run an `graphql-express` server:
`GraphQLError: Syntax Error: Cannot parse the unexpected character "/".`

Using a typedefs as a string and using only `graphql-tools` i got the following error:
`Error: "login" defined in resolvers, but not in schema`
Much easier to understand what went wrong.

Is it possible to expose these kinds of errors to the user when using `graphql-import`?

**Comment by kbrandwijk** [comment]
The only thing `graphql-import` does is process `# import` statements in schemas. I think this question should go into `graphql-yoga`, if you are experiencing it there.

**Comment by Nexxado** [comment]
Does `graphql-import` uses another library to parse `.graphql`/`.graphqls` files?

**Comment by Nexxado** [comment]
I found out what the issue was.
it seems that between `v0.1.9` and version `v0.3.1` you stopped supporting `.graphqls` files and only support `.graphql` files.

It's the added `isFile()` check found [here](https://github.com/graphcool/graphql-import/blob/master/src/index.ts#L18) that checks if the file has `graphql` extension name.

**Comment by koliyo** [comment]
Got the same error. Very confusing error message. Please add support for `.gql` extension as well.

**Comment by kbrandwijk** [comment]
@koliyo I agree to supporting `.gql`.
@Nexxado I don't think `.graphqls` is a standard extension. Where is that used?

**Comment by schickling** [comment]
I'm honestly not a big fan of supporting `.gql` as well. Are there any other languages that do so as well? I worry this could be confusing to beginners who now will think "hmm, that's the difference between `.graphql` and `.gql`".

**Comment by Nexxado** [comment]
@kbrandwijk [JS GraphQL](https://plugins.jetbrains.com/plugin/8097-js-graphql) plugin for Webstorm.

![screenshot_1](https://user-images.githubusercontent.com/12609607/36388332-2cf19364-15a4-11e8-88c4-f7e7fc74a048.png)

**Comment by kbrandwijk** [comment]
@schickling Supporting multiple extensions would not be confusing to beginners, if all the docs and gettings starteds just use `.graphql` as extension.

However, for more advanced users integrating this, that have existing files with a different extension, I see no harm in supporting it.

**Comment by vasco3** [comment]
I was using comments with `//` instead of `#` and that was causing the error...

**Comment by KeevanDance** [comment]
@kbrandwijk .graphqls seems to be the standard for a backend we are using built on `graphql-java-tools` @ https://github.com/graphql-java-kickstart/graphql-java-tools

**Comment by zzzgit** [comment]
OK, OK
If you guys don't want to make this tool to support `.gql` files, please add some more details to the error info.

![image](https://user-images.githubusercontent.com/1060733/49142689-5d105300-f334-11e8-84e5-182f0a480ed0.png)

This is what I currently get

**Comment by Glen-Moonpig** [comment]
I've just been stuck on this error for over an hour. Why do you even care what the file extension is? I'm telling the package my schema is in that file, the extension of that file is not important and should not be validated.

**Comment by ardatan** [comment]
Hi @jloveric , @TobiasBales , @wingertge , @jsonmaur and @SachaG  !
In 1.0.0 beta release, we introduced a lot of changes including different methods to load your schema such as URL Endpoint, graphql/gql files, TS/JS code files, Prisma endpoint, Apollo Engine and JSON files. And those files and sources of schema are parsed and validated in different ways thanks to GraphQL Toolkit which is used by the new version of GraphQL Import behind the scene

Could you install `graphql-import@beta` to try new changes? Don't forget to modify your code regarding to the migration notes in `README`. 
https://github.com/ardatan/graphql-import#updating-from-07x

**Comment by ardatan** [comment]
Available in 1.0.0!
