### ISSUE TITLE
When is the new release due ?

### ISSUE THREAD

**Issue by decebal** [ardatan/graphql-import#390]
My team is looking forward to using the latest graphql federation directives, do you guys have a status on a next release, I personally would love at least a minor release and if you need it, gladly offer my help towards making it happen.

**Comment by eadmundo** [comment]
Found this issue trying to get `graphql-import` to work with Apollo Federation! I see that there is #352 - which is merged and ready for release. Could we get a release of the package?

**Comment by eadmundo** [comment]
Also happy to contribute time & effort to getting the repo ready for release! Thanks

**Comment by ardatan** [comment]
Hi @ma-jahn !
In 1.0.0 beta release, we introduced a lot of changes including apollo federation support;
Could you install `graphql-import@beta` to try new changes? Don't forget to modify your code regarding to the migration notes in `README`. 
https://github.com/ardatan/graphql-import#updating-from-07xHi @ma-jahn !
In 1.0.0 beta release, we introduced a lot of changes including schema definition support;
Could you install `graphql-import@beta` to try new changes? Don't forget to modify your code regarding to the migration notes in `README`. 
https://github.com/ardatan/graphql-import#updating-from-07x
