### ISSUE TITLE
How can I comment out import statements?

### ISSUE THREAD

**Issue by marktani** [ardatan/graphql-import#43]
I want to "comment out" import statements, how does that work?

What about this:

```graphql
# import User from file.graphql
# # add later:
# # import Post from invalid.graphql
```

**Comment by kbrandwijk** [comment]
https://github.com/graphcool/graphql-import/blob/master/src/index.ts#L34

Your best bet is to change the word import 😄 

`# impport User from file.graphql` works fine

**Comment by tjpeden** [comment]
I've had success with
```
## import User from 'file.graphql'
```

**Comment by ardatan** [comment]
You can comment out `import` statements as @tjpeden suggests. Feel free to open a new issue if you have any problems.
