### ISSUE TITLE
Issues implementing library after v1.0.x beta update

### ISSUE THREAD

**Issue by dalvarez-r** [ardatan/graphql-import#454]
I've been using this library for a couple of months now. 
I'm using "apollo-server-express" and had no issue with the library prior to this beta update.

Just today I ran across an issue as the one referenced in #244, where I had multiples schemas using Query, Mutation and Subscription root types on each of the schemas which was giving me problems because of the duplicity of this root types.  I tried using "extends" to solve the problem but didn't work out.

After reading the docs, I found out about the recent beta update. After downloading it with NPM and adding it to my project It stopped working because of the new asynchronous nature of "importSchema".

This is how I used to do it:
(graphql.server.js)
```
const path = require('path');
const {makeExecutableSchema} = require('graphql-tools');
const {importSchema} = require('graphql-import');
// Resolvers
const resolvers = require('./resolvers/resolversMap');
// Directivas
const {AuthDirective} = require('./directives/auth.directives');
const {AuthorizationDirective} = require('./directives/authorization.directives');
// Schemas
const typeDefs = importSchema(path.resolve(__dirname, 'schemas', 'schema.graphql'));

// console.log({typeDefs});

const schema = makeExecutableSchema({
    typeDefs,
    resolvers,
    schemaDirectives: {
        auth: AuthDirective,
        authorization: AuthorizationDirective
    }
});
module.exports = schema;
```

and on app.js I would just call and consume the file:
```
const schema = require('./graphql/graphql-server');
const server = new ApolloServer({
    schema,
    ...
});
```

I'd love some assistance. Great library btw...

**Comment by ardatan** [comment]
Just use async/await with function then :)
```js
const path = require('path');
const {makeExecutableSchema} = require('graphql-tools');
const {importSchema} = require('graphql-import');
// Resolvers
const resolvers = require('./resolvers/resolversMap');
// Directivas
const {AuthDirective} = require('./directives/auth.directives');
const {AuthorizationDirective} = require('./directives/authorization.directives');


async function getSchema() {
// Schemas
const typeDefs = importSchema(path.resolve(__dirname, 'schemas', 'schema.graphql'));

// console.log({typeDefs});

const schema = makeExecutableSchema({
    typeDefs,
    resolvers,
    schemaDirectives: {
        auth: AuthDirective,
        authorization: AuthorizationDirective
    }
});
}

module.exports = getSchema;
```

```js
const getSchema = require('./graphql/graphql-server');

async function start() {

        const schema = await getSchema();
        const server = new ApolloServer({
             schema,
             ...
         });

}

start().catch(console.error);

```

If you have any issues, feel free to open a new issue.

**Comment by dalvarez-r** [comment]
Thanks to your help I figured the way to make it work!

It now also works (at least in my case) so that I can correctly use "extend" on my sub-level schemas!
Just a comment, I had to add an "await" on this part of your code:

```
async function getSchema() {
// Schemas
const typeDefs = **await** importSchema(path.resolve(__dirname, 'schemas', 'schema.graphql'));
...
```
Again, awesome library with awesome devs!
