### ISSUE TITLE
I am struggling with updating graphql-import to the latest version.

### ISSUE THREAD

**Issue by ybrhue** [ardatan/graphql-import#519]
Hi, I am using node.js, and somehow I can't really manage to update my index.js.

For example, what would I need to change here: https://github.com/tonsaito/graphql-bff so that it is working with the latest version?

**Comment by didaquis** [comment]
Take a look => https://github.com/ardatan/graphql-import#updating-from-07x

**Comment by ardatan** [comment]
It will be fixed in v1.0.0!
