### ISSUE TITLE
TypeError: Cannot read property 'location' of undefined

### ISSUE THREAD

**Issue by lynnic26** [ardatan/graphql-import#522]
```
const typeDefs = await importSchema('./schema.graphql');
```
version: graphql-import@v1.0.0-beta.2

**Comment by surfjedi** [comment]
Yes I am having this same error if the schema.graphql is not a sibling of the file(main.ts) that has "const typeDefs = await importSchema('../schema.graphql');" in it...

But I can get it to work by removing "../" in the file path and copying the "schema.graphql" file to the same directory as main.ts..
as in this:
"const typeDefs = await importSchema('schema.graphql');

NOTE: @lynnic26 mine desired file path is slightly off from yours I have issues with "../" as yorus appears to be "./"

**Comment by surfjedi** [comment]
@lynnic26 actually just got this working use path/join:

import { join } from "path";
const typeDefs = await importSchema(join(__dirname, "../schema.graphql"));

**Comment by lynnic26** [comment]
> @lynnic26 actually just got this working use path/join:
> 
> import { join } from "path";
> const typeDefs = await importSchema(join(__dirname, "../schema.graphql"));

Yes, I have figured out it.
anyway, thx
