### ISSUE TITLE
Semver version number format

### ISSUE THREAD

**Issue by dacioromero** [ardatan/graphql-import#525]
`alpha` pre-releases [the semver spec](https://semver.org/) more closely. For example `1.0.0-130487b.0` would be better versioned as `1.0.0-alpha.247` (its the 248th alpha release) so that `^1.0.0-alpha.247` would match later versions. If git hashes are desired it should be put after a `+` so that it is parsed as build metadata.

Currently `1.0.0-beta.2` is tagged as both `beta` and `lastest`. If `1.0.0` is meant to be in beta `0.7.1` should be tagged as `latest` instead until `1.0.0` is ready.

I appreciate the continued support of this very useful package.

**Comment by ardatan** [comment]
Available in 1.0.0!
