### ISSUE TITLE
CHANGELOG missing

### ISSUE THREAD

**Issue by MichaelDeBoey** [ardatan/graphql-import#539]
I just saw the package is updated to `v1.0.1`, but I can't find any CHANGELOG to check out the changes.

Would you be so kind to provide us with a decent CHANGELOG please? 🙂

Thanks for all your hard work @ardatan! 🙂

**Comment by ardatan** [comment]
Done!

**Comment by MichaelDeBoey** [comment]
Thanks @ardatan! 👊

**Comment by MichaelDeBoey** [comment]
@ardatan Could you also add a changelog for `v1.0.0` please?

At this point we can't see what's causing the breaking change.
Thanks!

**Comment by ardatan** [comment]
There is no much difference between those two versions. And there is no breaking change but internal refactor.

**Comment by MichaelDeBoey** [comment]
Still would be helpful for other people to see this in the changelog I think. 🙂

**Comment by ardatan** [comment]
Ok I added :)

**Comment by MichaelDeBoey** [comment]
Thanks @ardatan! 👊
