### ISSUE TITLE
Drop @graphql-toolkit/prisma-loader dependency

### ISSUE THREAD

**Issue by gajus** [ardatan/graphql-import#562]
`@graphql-toolkit/prisma-loader@0.9.8` depends on `prisma-yml@1.34.10`, which depends on `http-proxy-agent@2.1.0`, which makes HTTP proxies unusable.

Related issue:

* https://github.com/sindresorhus/got/issues/1039

**Comment by gajus** [comment]
For others stuck here, the last working version of graphql-import is v0.7.1.

**Comment by ardatan** [comment]
Fixed in v1.0.2
